@startuml
class AnswerViewModel {
    - _content : string = ""
    - _locked : bool = false
    + Content : string <<get>> <<set>>
    + Locked : bool <<get>> <<set>>
}
ViewModelBase <|-- AnswerViewModel
AnswerViewModel --> "Answer" Answer
@enduml
