@startuml
class SettingsViewModel {
    + SettingsViewModel()
    + SettingsViewModel(settings:Settings)
}
ViewModelBase <|-- SettingsViewModel
SettingsViewModel --> "_settings" Settings
SettingsViewModel --> "Settings" Settings
@enduml
