@startuml
class GameView <<partial>> {
    + GameView()
    - RebuildLetterGrid() : void
    - ShowStatus() : void
    # <<override>> OnLoaded() : void
    - NewGame_OnPointerReleased(sender:object?, e:PointerReleasedEventArgs) : void
    - Settings_OnPointerReleased(sender:object?, e:PointerReleasedEventArgs) : void
}
UserControl <|-- GameView
@enduml
