@startuml
class SettingsView <<partial>> {
    + SettingsView()
    - InitializeComponent() : void
    - Close_OnPointerReleased(sender:object?, e:PointerReleasedEventArgs) : void
    - WordLength_OnValueChanged(sender:object?, e:NumericUpDownValueChangedEventArgs) : void
    - MaxAnswers_OnValueChanged(sender:object?, e:NumericUpDownValueChangedEventArgs) : void
}
UserControl <|-- SettingsView
@enduml
