@startuml
class GameState {
    + CurrentTry : int
    + GameState(settings:Settings)
}
class "List`1"<T> {
}
GameState --> "CorrectAnswer" Answer
GameState --> "Answers<Answer>" "List`1"
GameState --> "Settings" Settings
GameState o-> "_random" Random
@enduml
