@startuml
class Settings <<record>> <<struct>> {
    + _wordLength : int = 5
    + _maxAnswers : int = 5
    + WordLength : int <<get>> <<set>>
    + MaxAnswers : int <<get>> <<set>>
    + Settings()
}
@enduml
